name: build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  core-tests:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v5
      - name: Configure, build, and test with Ninja and MSVC
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=x64 -host_arch=x64
          cmake --preset vs2022-core-tests
          cmake --build --preset vs2022-core-tests
          ctest --preset vs2022-core-tests
